### ISSUE TITLE
clashes with orion.js

### ISSUE THREAD

**Issue by javascriptpoet** [meteor-blog/meteor-blog#240]
i think it is due to the orion using nicolaslopezj:roles package. here is the error stack i get:
 Error: A method named '/roles/insert' is already defined
W20160123-19:43:56.988(-7)? (STDERR)     at livedata_server.js:1542:15
W20160123-19:43:56.988(-7)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
W20160123-19:43:56.988(-7)? (STDERR)     at [object Object]._.extend.methods (livedata_server.js:1538:7)
W20160123-19:43:56.988(-7)? (STDERR)     at [object Object].Mongo.Collection._defineMutationMethods (packages/mongo/collection.js:927:1)
W20160123-19:43:56.989(-7)? (STDERR)     at new Mongo.Collection (packages/mongo/collection.js:218:1)
W20160123-19:43:56.989(-7)? (STDERR)     at Roles.keys (packages/nicolaslopezj_roles/roles.js:17:1)
W20160123-19:43:56.989(-7)? (STDERR)     at /home/dmitry/IdeaProjects/simpleTest/.meteor/local/build/programs/server/packages/nicolaslopezj_roles.js:463:4
W20160123-19:43:56.989(-7)? (STDERR)     at /home/dmitry/IdeaProjects/simpleTest/.meteor/local/build/programs/server/packages/nicolaslopezj_roles.js:607:3
W20160123-19:43:56.989(-7)? (STDERR)     at /home/dmitry/IdeaProjects/simpleTest/.meteor/local/build/programs/server/boot.js:242:10
W20160123-19:43:56.989(-7)? (STDERR)     at Array.forEach (native)

list of packages:
meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
blaze-html-templates    # Compile .html files into Meteor Blaze views
session                 # Client-side reactive dictionary for your app
jquery                  # Helpful client-side library
tracker                 # Meteor's client-side reactive programming library

standard-minifiers      # JS/CSS minifiers run for production mode
es5-shim                # ECMAScript 5 compatibility for older browsers.
ecmascript              # Enable ECMAScript2015+ syntax in app code

autopublish             # Publish all data to the clients (for prototyping)
insecure                # Allow all DB writes from clients (for prototyping)
peerlibrary:fs
twbs:bootstrap
ryw:blog
iron:router
orionjs:core
fortawesome:fontawesome
orionjs:bootstrap

**Comment by javascriptpoet** [comment]
Never mind. its not a big deal. i can change it to use alanning:roles instead.
